### ISSUE TITLE
ListBox implementation, Demo and README

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/vaadin-list-box-flow#1]
Java API for the  https://github.com/vaadin/vaadin-list-box.  same demo and Readme same like other components. 

Since this is a selection component, it should be usable with `Binder`. This component needs a bit design to figure out the API for it, and how it should be generalized. 

```ListBox<T> implements SingleSelect<T> { .. }```

**Comment by pleku** [comment]
The implementation and API should be very similar to `RadioButtonGroup`.
The shared parts between `ListBox` and `RadioButtonGroup` should be moved to `com.vaadin.flow.component` in `flow-server` to mixin interfaces.

The naming for those interfaces is not yet decided.

### Acceptance Criteria
- There is a demo for ListBox showcasing the basic features
  - selection
  - disabled items
  - using components between items
