### ISSUE TITLE
"Flow documentation" link in README.md is broken

### ISSUE THREAD

**Issue by Haprog** [vaadin/vaadin-list-box-flow#13]
"Flow documentation" links to https://github.com/vaadin/flow/blob/master/flow-documentation/Overview.asciidoc but it should maybe link to here instead: https://github.com/vaadin/flow-and-components-documentation/blob/master/Overview.asciidoc ?

But it would be better to link directly to a documentation section that is about ListBox if there is such documentation? I didn't find any.

**Comment by pleku** [comment]
Should probably just link to the element page in vaadin.com and flow documentation in vaadin.com.

**Comment by ZheSun88** [comment]
linked to `flow-and-component-documentation`  at the moment. same happened with all the other components. 

ticket closed
