### ISSUE TITLE
Setup 2.0 branch for maintenance purpose

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/vaadin-list-box-flow#56]
currently, the `master` branch has been bumped to `2.1-SNAPSHOT`

for maintenance purpose, we should have a `2.0` branch which doesn't contain the new feature, `MultiSelectListBox`.

also a 2.0-Snapshot release configuration is needed.

**Comment by web-padawan** [comment]
There is a 2.0 branch now. Updated snapshot configuration for 14.0 to use it.
